#!/bin/bash
# Build Android AAB using native Gradle (no Expo/EAS).
# Prerequisites: ANDROID_HOME set, sdkmanager packages installed.
#
# Output: android/app/build/outputs/bundle/release/app-release.aab

set -e

# SDK path (edit if your SDK is elsewhere)
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Android}"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

cd "$(dirname "$0")"

# 1. Generate android/ if needed (Expo project - android is generated by prebuild)
if [ ! -d "android" ] || [ ! -f "android/build.gradle" ]; then
  echo "Generating android/ with expo prebuild..."
  npx expo prebuild --platform android --clean
fi

# 2. Ensure google-services.json exists for Firebase
if [ ! -f "google-services.json" ]; then
  echo "❌ google-services.json missing. Add it from Firebase Console."
  exit 1
fi

# 3. Write local.properties for Gradle
mkdir -p android
echo "sdk.dir=$ANDROID_HOME" > android/local.properties

# 4. Build AAB (run from project root so Node finds node_modules)
echo "Building AAB..."
./android/gradlew -p android bundleRelease

echo ""
echo "✅ AAB built successfully:"
echo "   android/app/build/outputs/bundle/release/app-release.aab"
