#!/bin/bash
# Run Expo Android build with correct SDK path
export ANDROID_HOME=/home/bikash/Android

# Check inotify limit (fixes ENOSPC: System limit for number of file watchers reached)
if [ -f /proc/sys/fs/inotify/max_user_watches ]; then
  WATCHES=$(cat /proc/sys/fs/inotify/max_user_watches)
  if [ "$WATCHES" -lt 524288 ] 2>/dev/null; then
    echo "⚠️  File watcher limit is low ($WATCHES). Metro may fail with ENOSPC."
    echo "   Run once (requires password): sudo sysctl fs.inotify.max_user_watches=524288"
    echo "   To make permanent: echo 'fs.inotify.max_user_watches=524288' | sudo tee -a /etc/sysctl.conf && sudo sysctl -p"
    echo ""
  fi
fi
export NODE_ENV=development
export BASE_URL=https://outix.co/apis
export EXPO_PUBLIC_BASE_URL=https://outix.co/apis
export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

# Firebase required for Android push tokens
if [ ! -f "google-services.json" ]; then
  echo "❌ google-services.json is missing!"
  echo ""
  echo "Android push notifications require Firebase. Add the file:"
  echo "  1. Go to https://console.firebase.google.com/"
  echo "  2. Project Settings → Your apps → Add Android app"
  echo "  3. Package name: com.live.outix"
  echo "  4. Download google-services.json"
  echo "  5. Place it in the project root: $(pwd)/google-services.json"
  echo "  6. Run: npx expo prebuild --clean"
  echo ""
  echo "See docs/FIREBASE-SETUP.md for details."
  exit 1
fi

# Ensure Firebase config is in the native build (needed after adding google-services.json)
if [ ! -f "android/app/google-services.json" ]; then
  echo "📦 Running prebuild to apply Firebase config..."
  npx expo prebuild --platform android --clean
fi

# Set SDK path for Gradle (android folder may be regenerated by prebuild)
mkdir -p android
echo "sdk.dir=/home/bikash/Android" > android/local.properties

# Check for connected device
if ! adb devices | grep -q "device$"; then
  echo "⚠️  No Android device connected."
  echo "Connect your phone via USB with USB debugging enabled, or start an emulator."
  echo ""
  echo "Run: adb devices"
  exit 1
fi

# Forward localhost:3000 from device to host (so app can reach local backend)
# Required when using a physical device - localhost on device = device itself
adb reverse tcp:3000 tcp:3000 2>/dev/null || true

npx expo run:android "$@"
