/**
 * Device Token Management
 *
 * Uses iOS native device token (APNs token) from Apple for all device identification.
 * The token is:
 * - Generated by iOS AppDelegate and received via native bridge
 * - Stored in AsyncStorage as 'APNsDeviceToken' (managed by iosDeviceTokenManager)
 * - Persists across app reloads, restarts, and kills
 * - Cleared only when app is uninstalled
 * - Uses in-memory cache and prevents race conditions
 * - Same token used everywhere in the app
 */

import AsyncStorage from "@react-native-async-storage/async-storage";

// Use the same storage key as iosDeviceTokenManager
const APNS_DEVICE_TOKEN_KEY = "APNsDeviceToken";

// In-memory cache to avoid multiple reads from AsyncStorage
let cachedToken: string | null = null;

// Promise to prevent race conditions during token retrieval
let tokenRetrievalPromise: Promise<string> | null = null;

/**
 * Get the device token - uses iOS native APNs token from Apple
 * Retrieves the token stored in AsyncStorage by iosDeviceTokenManager
 * Uses in-memory cache and prevents race conditions
 *
 * @returns Promise<string> - The iOS device token (APNs token from Apple)
 * @throws Error if token is not available
 */
export const getDeviceToken = async (): Promise<string> => {
  // Return cached token if available
  if (cachedToken) {
    return cachedToken;
  }

  // If token is currently being retrieved, wait for it
  if (tokenRetrievalPromise) {
    return tokenRetrievalPromise;
  }

  // Start new token retrieval
  tokenRetrievalPromise = (async () => {
    try {
      // Get iOS device token from AsyncStorage (same key used by iosDeviceTokenManager)
      const token = await AsyncStorage.getItem(APNS_DEVICE_TOKEN_KEY);

      if (!token) {
        throw new Error(
          "Device token not available. Make sure iOS device token has been received from AppDelegate and stored in AsyncStorage."
        );
      }

      console.log("[DEVICE-TOKEN] ✅ Retrieved iOS APNs token from AsyncStorage");
      cachedToken = token;
      return token;
    } catch (error) {
      cachedToken = null; // Clear cache on error
      console.error("[DEVICE-TOKEN] ❌ Error getting device token:", error);
      throw error;
    } finally {
      tokenRetrievalPromise = null; // Reset promise
    }
  })();

  return tokenRetrievalPromise;
};

/**
 * Clear the device token (for testing/debugging only)
 * WARNING: This will break all subscriptions!
 * Clears both in-memory cache and AsyncStorage
 */
export const clearDeviceToken = async (): Promise<void> => {
  try {
    // Clear AsyncStorage (same key used by iosDeviceTokenManager)
    await AsyncStorage.removeItem(APNS_DEVICE_TOKEN_KEY);
    cachedToken = null; // Clear in-memory cache
    console.log("[DEVICE-TOKEN] 🧹 Device token cleared from AsyncStorage and cache");
  } catch (error) {
    console.error("[DEVICE-TOKEN] ❌ Error clearing device token:", error);
    throw error;
  }
};
